"""add event and user model

Revision ID: 271c2b9a875b
Revises: 802caa7a1ed0
Create Date: 2023-10-28 16:48:36.960879

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '271c2b9a875b'
down_revision: Union[str, None] = '802caa7a1ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    facilityspec_type = sa.Enum('lecture', 'lab_or_prac', 'unknown', name='facilityspec')
    facilityspec_type.create(op.get_bind(), checkfirst=False)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('subgroup', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('begin', sa.TIMESTAMP(), nullable=True),
    sa.Column('end', sa.TIMESTAMP(), nullable=True),
    sa.Column('facility', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('teacher', sa.TEXT(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('subgroup', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['facility'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('facility', sa.Column('spec', facilityspec_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'spec')
    op.drop_table('event')
    op.drop_table('client')
    # ### end Alembic commands ###
