"""add field 'changed' to an event

Revision ID: 81d9e8c4cfb5
Revises: bd5bf94b3f35
Create Date: 2023-10-28 20:05:00.421111

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81d9e8c4cfb5'
down_revision: Union[str, None] = 'bd5bf94b3f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('changed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'changed')
    # ### end Alembic commands ###
