"""add subgroups_count to model group

Revision ID: bd5bf94b3f35
Revises: 271c2b9a875b
Create Date: 2023-10-28 17:39:45.268823

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd5bf94b3f35'
down_revision: Union[str, None] = '271c2b9a875b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column(
        'subgroups_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'subgroups_count')
    # ### end Alembic commands ###
