"""event model delete fks

Revision ID: bf5e0e0946ff
Revises: fbf109745469
Create Date: 2023-10-28 22:36:22.796407

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf5e0e0946ff'
down_revision: Union[str, None] = 'fbf109745469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_group_fkey', 'event', type_='foreignkey')
    op.drop_constraint('event_teacher_fkey', 'event', type_='foreignkey')
    op.drop_constraint('event_facility_fkey', 'event', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('event_facility_fkey', 'event',
                          'facility', ['facility'], ['name'])
    op.create_foreign_key('event_teacher_fkey', 'event',
                          'teacher', ['teacher'], ['name'])
    op.create_foreign_key('event_group_fkey', 'event',
                          'group', ['group'], ['name'])
    # ### end Alembic commands ###
