"""add special_event, upd user, add subgroup

Revision ID: 60eace25eb3e
Revises: e251ae4cd51c
Create Date: 2023-11-15 02:51:44.000050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60eace25eb3e'
down_revision: Union[str, None] = 'e251ae4cd51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('group', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('group', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('color', sa.TEXT(), nullable=True))
    op.add_column('client', sa.Column('theme', sa.TEXT(), nullable=True))
    op.drop_column('client', 'password')
    op.drop_column('group', 'subgroups_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('subgroups_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('client', 'theme')
    op.drop_column('client', 'color')
    op.drop_table('subgroup')
    op.drop_table('special_group')
    # ### end Alembic commands ###
