"""fix user model

Revision ID: c2d52f616946
Revises: 60eace25eb3e
Create Date: 2023-11-15 04:05:20.875046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d52f616946'
down_revision: Union[str, None] = '60eace25eb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_group_fkey', 'client', type_='foreignkey')
    op.alter_column('client', 'group',
               existing_type=sa.INTEGER(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('client_group_fkey', 'client', 'group', ['group'], ['id'])
    op.alter_column('client', 'group',
               existing_type=sa.TEXT(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('client', 'type')
    # ### end Alembic commands ###
